/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({
  id: '/conditions-utilisation',
  path: '/conditions-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/profiles': typeof ProfilesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/profiles': typeof ProfilesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/premium': typeof PremiumRoute
  '/profiles': typeof ProfilesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/confidentialite'
    | '/conditions-utilisation'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentions-legales'
    | '/premium'
    | '/profiles'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/confidentialite'
    | '/conditions-utilisation'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentions-legales'
    | '/premium'
    | '/profiles'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/confidentialite'
    | '/conditions-utilisation'
    | '/contact'
    | '/events'
    | '/join'
    | '/mentions-legales'
    | '/premium'
    | '/profiles'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PremiumRoute: typeof PremiumRoute
  ProfilesRoute: typeof ProfilesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-utilisation': {
      id: '/conditions-utilisation'
      path: '/conditions-utilisation'
      fullPath: '/conditions-utilisation'
      preLoaderRoute: typeof ConditionsUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConditionsUtilisationRoute: ConditionsUtilisationRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PremiumRoute: PremiumRoute,
  ProfilesRoute: ProfilesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
